pipeline {
   agent any

   tools {
     maven 'maven3'
     jdk 'jdk17'
   }
   
   environment {
    IMAGE_NAME = "java-gui-app"
   }

   stages {

    stage('build with maven') {
        steps {
            dir('Projects/java-gui-app') {
            sh 'mvn clean package'
            }

        }
    }

    stage('Sonarqube analysis') {
        steps {
            withSonarQubeEnv('SonarQube') {
                sh 'mvn sonar:sonar'
            }
        }
    }

    stage('Build docker images') {
        steps {
            sh 'docker build -t java-gui-app:v1 .'
        }
    }

    stage('Run container') {
        steps {
            sh '''
            docker stop java-gui-app || true
            docker rm java-gui-app || true
            docker run --name java-gui-app --rm -p 3005:3005 java-gui-app:v1
            '''
        }
    }
  }
}
